### ISSUE TITLE
卧槽 你的头像！！！

### ISSUE THREAD

**Issue by ice1000** [Predator-SD/Image_Processing_AI_Library#1]
你是不是看了fsn
还是fz？
卧槽 居然是Saber

**Comment by Predator-SD** [comment]
ubw

**Comment by ice1000** [comment]
....赶紧去看[Fate Zero](http://www.bilibili.com/video/av1608918/)

**Comment by Predator-SD** [comment]
。。。准备补完fzn再看zero

**Comment by ice1000** [comment]
你特么还没补完。。。。![pic](https://github.com/ice1000/dialogs/blob/master/raw/cai_0x01.jpg)

**Comment by Predator-SD** [comment]
现在补完了，正在看zero

**Comment by ice1000** [comment]
赶紧看
~~看完FZ去玩沙耶之歌吧~~
